# Generated by Django 5.2.8 on 2025-11-08 18:54

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название филиала')),
                ('address', models.TextField(verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('rent', 'Аренда'), ('utilities', 'Коммунальные услуги'), ('office', 'Офисные нужды'), ('taxes', 'Налоги'), ('other', 'Прочее')], max_length=20, verbose_name='Категория')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('date', models.DateField(verbose_name='Дата расхода')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Расход',
                'verbose_name_plural': 'Расходы',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Администратор'), ('teacher', 'Преподаватель'), ('student', 'Студент')], default='student', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название группы')),
                ('lesson_duration', models.IntegerField(default=60, verbose_name='Длительность занятия (мин)')),
                ('lesson_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Стоимость занятия')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.branch', verbose_name='Филиал')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_start', models.DateTimeField(verbose_name='Начало занятия')),
                ('datetime_end', models.DateTimeField(verbose_name='Конец занятия')),
                ('status', models.CharField(choices=[('scheduled', 'Запланировано'), ('completed', 'Проведено'), ('cancelled', 'Отменено'), ('postponed', 'Перенесено')], default='scheduled', max_length=10, verbose_name='Статус')),
                ('type', models.CharField(choices=[('group', 'Групповое'), ('individual', 'Индивидуальное')], max_length=10, verbose_name='Тип занятия')),
                ('format', models.CharField(choices=[('offline', 'Офлайн'), ('online', 'Онлайн')], max_length=10, verbose_name='Формат')),
                ('topic', models.CharField(blank=True, max_length=200, null=True, verbose_name='Тема занятия')),
                ('homework', models.TextField(blank=True, null=True, verbose_name='Домашнее задание')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Регулярное занятие')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.branch', verbose_name='Филиал')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.course', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Занятие',
                'verbose_name_plural': 'Занятия',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('telegram_chat_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram Chat ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='ФИО родителя')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Скидка (%)')),
                ('format', models.CharField(choices=[('offline', 'Офлайн'), ('online', 'Онлайн')], default='offline', max_length=10, verbose_name='Формат обучения')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.branch', verbose_name='Филиал')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crm.profile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата оплаты')),
                ('purpose', models.CharField(max_length=200, verbose_name='Назначение платежа')),
                ('lessons_paid', models.ManyToManyField(blank=True, to='crm.lesson', verbose_name='Оплаченные занятия')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.student', verbose_name='Студент (индив.)'),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(to='crm.student', verbose_name='Студенты'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Присутствовал'), ('late', 'Опоздал'), ('sick', 'Отсутствует по болезни'), ('absent_no_reason', 'Отсутствует без предупреждения')], default='present', max_length=20, verbose_name='Статус посещения')),
                ('student_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий по студенту')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.lesson', verbose_name='Занятие')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Посещаемость',
                'verbose_name_plural': 'Посещаемость',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.TextField(verbose_name='Образование')),
                ('experience', models.TextField(verbose_name='Опыт работы')),
                ('certificates', models.TextField(blank=True, null=True, verbose_name='Сертификаты')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ставка в час')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crm.profile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.teacher', verbose_name='Преподаватель'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.teacher', verbose_name='Преподаватель'),
        ),
        migrations.CreateModel(
            name='TeacherSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_start', models.DateTimeField(verbose_name='Начало слота')),
                ('datetime_end', models.DateTimeField(verbose_name='Конец слота')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Свободный слот преподавателя',
                'verbose_name_plural': 'Свободные слоты преподавателей',
            },
        ),
    ]
