# Generated by Django 5.2.8 on 2026-06-24 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='capacity',
            field=models.PositiveIntegerField(default=8, verbose_name='Максимум студентов'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_open_for_booking',
            field=models.BooleanField(default=True, verbose_name='Открыта для записи'),
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта'), ('transfer', 'Банковский перевод')], default='cash', max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.AddField(
            model_name='expense',
            name='receipt_image',
            field=models.FileField(blank=True, null=True, upload_to='receipts/', verbose_name='Чек'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина отмены'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='cancellation_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время отмены'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='custom_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Индивидуальная ставка'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_penalty_applied',
            field=models.BooleanField(default=False, verbose_name='Штраф применен'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='recurring_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество повторов'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='recurring_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания повторов'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='recurring_parent_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID родительского занятия'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='recurring_type',
            field=models.CharField(blank=True, choices=[('weekly', 'Еженедельно'), ('biweekly', 'Раз в 2 недели'), ('monthly', 'Ежемесячно')], max_length=20, null=True, verbose_name='Тип повтора'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='sick_leave_provided',
            field=models.BooleanField(default=False, verbose_name='Справка предоставлена'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='substitute_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Ставка замены'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='substitute_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substitute_lessons', to='crm.teacher', verbose_name='Преподаватель на замену'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта'), ('transfer', 'Банковский перевод')], default='cash', max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер чека'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='bank_account',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Банковский счет'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата найма'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(max_length=100, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.RemoveField(
            model_name='payment',
            name='lessons_paid',
        ),
        migrations.AlterField(
            model_name='payment',
            name='purpose',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Назначение'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Базовая ставка в час'),
        ),
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('mode', models.CharField(choices=[('group', 'В группу'), ('individual', 'Индивидуально к преподавателю')], max_length=12, verbose_name='Тип записи')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий клиента')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('confirmed', 'Подтверждена'), ('rejected', 'Отклонена')], default='new', max_length=12, verbose_name='Статус')),
                ('manager_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий менеджера')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.branch', verbose_name='Филиал')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.course', verbose_name='Группа')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Заявка на запись',
                'verbose_name_plural': 'Заявки на запись',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Создание'), ('update', 'Изменение'), ('delete', 'Удаление'), ('status_change', 'Смена статуса')], max_length=20, verbose_name='Действие')),
                ('old_data', models.JSONField(blank=True, null=True, verbose_name='Старые данные')),
                ('new_data', models.JSONField(blank=True, null=True, verbose_name='Новые данные')),
                ('changed_fields', models.JSONField(blank=True, null=True, verbose_name='Измененные поля')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='crm.lesson', verbose_name='Занятие')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог занятия',
                'verbose_name_plural': 'Логи занятий',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('type', models.CharField(choices=[('debt', 'О долге'), ('schedule', 'О расписании'), ('payment', 'Об оплате'), ('custom', 'Свое')], default='custom', max_length=20, verbose_name='Тип')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='crm.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='lessons_paid',
            field=models.IntegerField(default=1, verbose_name='Оплачено занятий'),
        ),
        migrations.CreateModel(
            name='CancellationNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.lesson', verbose_name='Занятие')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь (админ/учитель)')),
            ],
            options={
                'verbose_name': 'Уведомление об отмене',
                'verbose_name_plural': 'Уведомления об отменах',
                'unique_together': {('lesson', 'user')},
            },
        ),
    ]
