# Generated by Django 5.2.8 on 2026-08-17 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_course_capacity_course_is_open_for_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='homework_audio',
            field=models.FileField(blank=True, null=True, upload_to='homework_audio/', verbose_name='Аудио ДЗ'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='homework_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий учителя к ДЗ'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='homework_status',
            field=models.CharField(choices=[('not_required', 'Не требуется'), ('pending', 'Ожидает сдачи'), ('submitted', 'Сдано'), ('checked', 'Проверено'), ('needs_revision', 'Требует доработки')], default='not_required', max_length=20, verbose_name='Статус ДЗ'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_homework_completed',
            field=models.BooleanField(default=False, verbose_name='ДЗ выполнено'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='homework',
            field=models.TextField(blank=True, null=True, verbose_name='Текст ДЗ'),
        ),
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_level', models.CharField(blank=True, max_length=5, null=True, verbose_name='Текущий уровень (A1-C2)')),
                ('current_module', models.CharField(blank=True, max_length=100, null=True, verbose_name='Текущий модуль/тема')),
                ('overall_progress', models.FloatField(default=0.0, verbose_name='Общий прогресс (%)')),
                ('streak_days', models.IntegerField(default=0, verbose_name='Дней занятий подряд')),
                ('last_activity_date', models.DateField(blank=True, null=True, verbose_name='Дата последней активности')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='crm.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Прогресс студента',
                'verbose_name_plural': 'Прогресс студентов',
            },
        ),
    ]
