# Generated by Django 5.2.8 on 2026-08-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_lesson_homework_audio_lesson_homework_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprogress',
            name='course_total_lessons',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Всего занятий в курсе'),
        ),
    ]
