# Generated by Django 5.2.8 on 2026-08-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_studentprogress_course_total_lessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='homework_file',
            field=models.FileField(blank=True, null=True, upload_to='homework_files/', verbose_name='Файл ДЗ (PDF/PNG/DOC)'),
        ),
    ]
