# Generated by Django 5.2.8 on 2026-08-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_lesson_homework_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Оплачено'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость занятия'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Запланировано'), ('completed', 'Проведено'), ('cancelled', 'Отменено'), ('postponed', 'Перенесено'), ('missed', 'Пропущено'), ('no_show', 'Не явился'), ('paid', 'Оплачено'), ('debt', 'Долг')], default='scheduled', max_length=10, verbose_name='Статус'),
        ),
    ]
