# Generated by Django 5.2.8 on 2026-08-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_add_lesson_price_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Запланировано'), ('pending', 'Ожидает подтверждения'), ('completed', 'Проведено'), ('cancelled', 'Отменено'), ('postponed', 'Перенесено'), ('missed', 'Пропущено'), ('no_show', 'Не явился'), ('paid', 'Оплачено'), ('debt', 'Долг')], default='scheduled', max_length=10, verbose_name='Статус'),
        ),
    ]
